Medicine/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from medicine_app import views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('medicine_app/', include('medicine_app.urls')),
    path('register/', user_views.register, name='register'),
<<<<<<< HEAD
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', views.index, name='index'),
    path('dorixona/', views.dorixona),
=======
>>>>>>> 327daf35b2d0513c826944c9ff5bbc4dd0464486
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medicine_app/urls.py
from django.urls import path
from . import views

app_name = "medicine_app"

urlpatterns=[
    path('<int:pk>',views.detail, name="detail")
]

medicine_app/models.py
from django.db import models



class Medicine(models.Model):
    name = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=8, decimal_places=2)
<<<<<<< HEAD
# <<<<<<< HEAD
    photo = models.ImageField(blank=True, null=True)
# =======
# >>>>>>> 1808c2695b16b1404092ab9912ef90b00c86e232
=======
    photo = models.ImageField(blank=True, null=True)
>>>>>>> 327daf35b2d0513c826944c9ff5bbc4dd0464486
    quantity = models.IntegerField()
    available = models.BooleanField(default=False)
    description = models.TextField()

    def __str__(self):
        return "Name: {}   Price: {}   Quantity: {}   Avialable: {} ".format(self.name,self.price,self.quantity,self.available)

class User(models.Model):
    username = models.CharField(max_length=256)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    phone_number = models.IntegerField()
    email = models.EmailField(max_length=256)

class Card(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

class Cards_medicine(models.Model):
    cards_id = models.ForeignKey(Card, on_delete=models.CASCADE)
    medicine_id = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    count = models.IntegerField()

class User_address(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=256)
    zip_code = models.IntegerField()
    address1 = models.CharField(max_length=256)
    address2 = models.CharField(max_length=256)
    is_default = models.BooleanField()

class Order(models.Model):
    cards_id = models.ForeignKey(Card, on_delete=models.CASCADE)
    status_choices = (
    ('new','New Order'),
    ('accepted', 'Accepted'),
    ('in_progress','In progress'),
    ('comleted','Completed'),
    ('cancelled','Cancelled'),
    )
    status = models.CharField(max_length=20, choices=status_choices, default='new')
    payment_status_choices = (
        ('unpaid','Unpaid'),
        ('failed','Failed'),
        ('expired','Expired'),
        ('paid', 'Paid'),
        ('refunded', 'Refunded'),
    )
    payment_status = models.CharField(max_length=20, choices=payment_status_choices, default='unpaid')
    total_price = models.IntegerField()
    user_address_id = models.ForeignKey(User_address, on_delete=models.CASCADE)
    payment_method_choices = (
        ('cash', 'Cash'),
        ('payme', 'Payme')
    )
    payment_method = models.CharField(max_length=20, choices=payment_method_choices, default='cash')

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profie_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

medicine_app/views.py
from django.shortcuts import render
from medicine_app.models import Medicine

def index(request):
    medicines_list =  Medicine.objects.order_by('name')
    date_dict = {'access_record': medicines_list}
    return render(request,'medicine_app/index.html', context=date_dict)


def detail(request, pk):
    medicine_detail = Medicine.objects.get(pk=pk)
    data = {'details':medicine_detail}
    return render(request, 'medicine_app/detail.html', context=data)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Your account has been created! Now you can login')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


<<<<<<< HEAD
@login_required
def profile(request):
    return render(request, 'users/profile.html')
=======
messages.success    
>>>>>>> 327daf35b2d0513c826944c9ff5bbc4dd0464486

medicine_app/templates/medicine_app/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Medicine</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- Start your project here-->
<<<<<<< HEAD
  <!--Main Navigation-->
  <!--Main Navigation-->

  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'index' %}">Medicine</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'index' %}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Log In</a>
            <a class="nav-item nav-link">|</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <!--Main Navigation-->
  <!--Main Navigation-->
  <!-- Start your project here-->
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>

    </div>
  </main>

  <footer class="page-footer font-small special-color-dark pt-4" style="margin-top: 50%">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <i class="fab fa-twitter"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <i class="fab fa-google-plus-g"> </i>
          </a>
=======
<!--Main Navigation-->
<!--Main Navigation-->

<header>

  <nav class="navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#"><strong>Medicine</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li> -->
      </ul>
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
            <a class="nav-link"><i class="fa fa-shopping-cart"></i></a>
          </li>
        <li class="nav-item">
          <a class="nav-link"><i class="fab fa-facebook-f"></i></a>
>>>>>>> 327daf35b2d0513c826944c9ff5bbc4dd0464486
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1">
            <i class="fab fa-linkedin-in"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-dribbble mx-1">
            <i class="fab fa-dribbble"> </i>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->

    </div>
<<<<<<< HEAD
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> Medicine.com</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
=======
  </nav>
  <div class="container">
      {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
      {% endif %}
  </div>
</header>
<!-- Start your project here-->

<div class="container">
  <div style="margin:5px">
    {% block content %}

    {% endblock %}
  </div>
</div>


<footer class="page-footer font-small special-color-dark pt-4" style="margin-top: 50%">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> Medicine.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
>>>>>>> 327daf35b2d0513c826944c9ff5bbc4dd0464486


  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

</body>

</html>

medicine_app/templates/medicine_app/detail.html
{% extends "medicine_app/base.html" %}
{% block content %}
    <div class="row">
            <div class="col-3 orders">
                <div class="card" style="width: 17rem;">
                        <img class="card-img-top medicine" src="{{details.photo.url}}" alt="Card image cap" >
                    <div class="card-body">
                          <h5 class="card-title">{{details.name}}</h5>  <!-- DoriNomi -->
                          <h6>Price: {{ details.price }}</h6>  <!-- DoriNomi narxi -->
                          <h6>Existence: {% if details.available == True %} <span style="color:green"> Есть в наличии </span>{% else %} <span style="color: red"> Нет в наличии </span> {% endif %}</h6>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Quantity</span>
                            </div>
                            <input type="number" class="form-control" placeholder="Username" aria-label="Username" 
                            aria-describedby="basic-addon1" value="1">
                        </div>
                        <a href="#" class="btn btn-success">Add to cart</a>
                    </div>
                </div>
            </div>
        <div class="col-8 orders">
            <div class="jumbotron">
                <h3 class="display-6">Description</h3>
                <p class="lead">{{ details.description }}</p>                
            </div>
        </div>
    </div>
{% endblock %}

medicine_app/templates/medicine_app/index.html
<<<<<<< HEAD
{% extends 'medicine_app/base.html' %}
=======
{% extends "medicine_app/base.html" %}
{% block content %}

    <div class="d-flex flex-wrap" style="margin: 5px">
            {% for medicine in access_record %}
            
            <div class="card" style="width: 16rem; margin: 5px">
              
                <img src="{{ medicine.photo.url }}" class="card-img-top" alt="..." height="150px">
                    <div class="card-body">
                        <a href="{% url 'medicine_app:detail' pk=medicine.pk %}" class="card-title">{{medicine.name}}</a>
                        <h6>{{medicine.price}} сум</h6>
                    </div>
            </div>
            {% endfor %}
    </div>
{% endblock %}
>>>>>>> 327daf35b2d0513c826944c9ff5bbc4dd0464486

users/templates/users/login.html
{% extends 'medicine_app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<div class="content-section">
  <form class="" method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Login   </button>
      <div class="border-top pt-3">
        <small class="text-muted">Need an Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a></small>

      </div>
    </div>
  </form>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'medicine_app/base.html' %}

{% block content %}
<h2>You have been logged out </h2>
<div class="border-top pt-3">
  <small class="text-muted">
<a href="{% url 'login' %}">Log In Again</a>
  </small>


</div>


{% endblock content %}

users/templates/users/profile.html
{% extends 'medicine_app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <div class="media mt-5">
    <img class="rounded-circle" style="width: 200px;
    height: 187px;" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'medicine_app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<div class="content-section">
  <form class="" method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Us</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Sign Up</button>
      <div class="border-top pt-3">
        <small class="text-muted">Already Have an Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a></small>

      </div>
    </div>
  </form>
</div>
{% endblock content %}